from pathlib import Path

CACHE_DIR = Path(__file__).resolve().parent.parent / "cache"
CACHE_TTL_SECONDS = 4 * 60 * 60  # 4 saat

BIST100: list[dict[str, str]] = [
    # BIST-30
    {"symbol": "AKBNK", "name": "Akbank", "yahoo_symbol": "AKBNK.IS"},
    {"symbol": "ARCLK", "name": "Arçelik", "yahoo_symbol": "ARCLK.IS"},
    {"symbol": "ASELS", "name": "Aselsan", "yahoo_symbol": "ASELS.IS"},
    {"symbol": "BIMAS", "name": "BİM Mağazalar", "yahoo_symbol": "BIMAS.IS"},
    {"symbol": "EKGYO", "name": "Emlak Konut GYO", "yahoo_symbol": "EKGYO.IS"},
    {"symbol": "ENKAI", "name": "Enka İnşaat", "yahoo_symbol": "ENKAI.IS"},
    {"symbol": "EREGL", "name": "Ereğli Demir Çelik", "yahoo_symbol": "EREGL.IS"},
    {"symbol": "FROTO", "name": "Ford Otosan", "yahoo_symbol": "FROTO.IS"},
    {"symbol": "GARAN", "name": "Garanti BBVA", "yahoo_symbol": "GARAN.IS"},
    {"symbol": "GUBRF", "name": "Gübre Fabrikaları", "yahoo_symbol": "GUBRF.IS"},
    {"symbol": "HEKTS", "name": "Hektaş Ticaret", "yahoo_symbol": "HEKTS.IS"},
    {"symbol": "ISCTR", "name": "İş Bankası C", "yahoo_symbol": "ISCTR.IS"},
    {"symbol": "KCHOL", "name": "Koç Holding", "yahoo_symbol": "KCHOL.IS"},
    {"symbol": "KOZAA", "name": "Koza Altın", "yahoo_symbol": "KOZAA.IS"},
    {"symbol": "KOZAL", "name": "Koza Anadolu Metal", "yahoo_symbol": "KOZAL.IS"},
    {"symbol": "KRDMD", "name": "Kardemir D", "yahoo_symbol": "KRDMD.IS"},
    {"symbol": "MGROS", "name": "Migros Ticaret", "yahoo_symbol": "MGROS.IS"},
    {"symbol": "OYAKC", "name": "Oyak Çimento", "yahoo_symbol": "OYAKC.IS"},
    {"symbol": "PETKM", "name": "Petkim", "yahoo_symbol": "PETKM.IS"},
    {"symbol": "PGSUS", "name": "Pegasus", "yahoo_symbol": "PGSUS.IS"},
    {"symbol": "SAHOL", "name": "Sabancı Holding", "yahoo_symbol": "SAHOL.IS"},
    {"symbol": "SASA", "name": "SASA Polyester", "yahoo_symbol": "SASA.IS"},
    {"symbol": "SISE", "name": "Şişecam", "yahoo_symbol": "SISE.IS"},
    {"symbol": "TAVHL", "name": "TAV Havalimanları", "yahoo_symbol": "TAVHL.IS"},
    {"symbol": "TCELL", "name": "Turkcell", "yahoo_symbol": "TCELL.IS"},
    {"symbol": "THYAO", "name": "Türk Hava Yolları", "yahoo_symbol": "THYAO.IS"},
    {"symbol": "TKFEN", "name": "Tekfen Holding", "yahoo_symbol": "TKFEN.IS"},
    {"symbol": "TOASO", "name": "Tofaş Oto Fab.", "yahoo_symbol": "TOASO.IS"},
    {"symbol": "TUPRS", "name": "Tüpraş", "yahoo_symbol": "TUPRS.IS"},
    {"symbol": "YKBNK", "name": "Yapı Kredi", "yahoo_symbol": "YKBNK.IS"},
    # BIST-50 (ek 20)
    {"symbol": "AEFES", "name": "Anadolu Efes", "yahoo_symbol": "AEFES.IS"},
    {"symbol": "AGESA", "name": "Agesa Hayat Emeklilik", "yahoo_symbol": "AGESA.IS"},
    {"symbol": "AGHOL", "name": "AG Anadolu Grubu Holding", "yahoo_symbol": "AGHOL.IS"},
    {"symbol": "AKSA", "name": "Aksa Akrilik", "yahoo_symbol": "AKSA.IS"},
    {"symbol": "AKSEN", "name": "Aksa Enerji", "yahoo_symbol": "AKSEN.IS"},
    {"symbol": "ALARK", "name": "Alarko Holding", "yahoo_symbol": "ALARK.IS"},
    {"symbol": "ALFAS", "name": "Alfa Solar Enerji", "yahoo_symbol": "ALFAS.IS"},
    {"symbol": "BERA", "name": "Bera Holding", "yahoo_symbol": "BERA.IS"},
    {"symbol": "BIOEN", "name": "Biotrend Çevre ve Enerji", "yahoo_symbol": "BIOEN.IS"},
    {"symbol": "BRYAT", "name": "Borusan Yatırım", "yahoo_symbol": "BRYAT.IS"},
    {"symbol": "CANTE", "name": "Çan2 Termik", "yahoo_symbol": "CANTE.IS"},
    {"symbol": "CCOLA", "name": "Coca-Cola İçecek", "yahoo_symbol": "CCOLA.IS"},
    {"symbol": "CEMTS", "name": "Çemtaş Çelik", "yahoo_symbol": "CEMTS.IS"},
    {"symbol": "DOHOL", "name": "Doğan Holding", "yahoo_symbol": "DOHOL.IS"},
    {"symbol": "EGEEN", "name": "Ege Endüstri", "yahoo_symbol": "EGEEN.IS"},
    {"symbol": "EUPWR", "name": "Europower Enerji", "yahoo_symbol": "EUPWR.IS"},
    {"symbol": "GESAN", "name": "Giresun San. ve Tic.", "yahoo_symbol": "GESAN.IS"},
    {"symbol": "HALKB", "name": "Halkbank", "yahoo_symbol": "HALKB.IS"},
    {"symbol": "ISGYO", "name": "İş GYO", "yahoo_symbol": "ISGYO.IS"},
    {"symbol": "KONTR", "name": "Kontrolmatik", "yahoo_symbol": "KONTR.IS"},
    # BIST-100 (ek 50)
    {"symbol": "AKENR", "name": "Akenerji Elektrik", "yahoo_symbol": "AKENR.IS"},
    {"symbol": "ALBRK", "name": "Albaraka Türk", "yahoo_symbol": "ALBRK.IS"},
    {"symbol": "ANSGR", "name": "Anadolu Sigorta", "yahoo_symbol": "ANSGR.IS"},
    {"symbol": "ARDYZ", "name": "Ard Grup Bilişim", "yahoo_symbol": "ARDYZ.IS"},
    {"symbol": "ASTOR", "name": "Astor Enerji", "yahoo_symbol": "ASTOR.IS"},
    {"symbol": "AYDEM", "name": "Aydem Enerji", "yahoo_symbol": "AYDEM.IS"},
    {"symbol": "BAGFS", "name": "Bagfaş Gübre", "yahoo_symbol": "BAGFS.IS"},
    {"symbol": "BASGZ", "name": "Başkent Doğalgaz", "yahoo_symbol": "BASGZ.IS"},
    {"symbol": "BTCIM", "name": "Batıçim", "yahoo_symbol": "BTCIM.IS"},
    {"symbol": "BUCIM", "name": "Bursa Çimento", "yahoo_symbol": "BUCIM.IS"},
    {"symbol": "CIMSA", "name": "Çimsa Çimento", "yahoo_symbol": "CIMSA.IS"},
    {"symbol": "CWENE", "name": "CW Enerji", "yahoo_symbol": "CWENE.IS"},
    {"symbol": "DOAS", "name": "Doğuş Otomotiv", "yahoo_symbol": "DOAS.IS"},
    {"symbol": "ECILC", "name": "Eczacıbaşı İlaç", "yahoo_symbol": "ECILC.IS"},
    {"symbol": "ENJSA", "name": "Enerjisa Enerji", "yahoo_symbol": "ENJSA.IS"},
    {"symbol": "ENERY", "name": "Enerji Yatırımları", "yahoo_symbol": "ENERY.IS"},
    {"symbol": "ESEN", "name": "Esenboğa Elektrik", "yahoo_symbol": "ESEN.IS"},
    {"symbol": "GENIL", "name": "Gen İlaç", "yahoo_symbol": "GENIL.IS"},
    {"symbol": "GLYHO", "name": "Global Yatırım Holding", "yahoo_symbol": "GLYHO.IS"},
    {"symbol": "GOLTS", "name": "Göltaş Çimento", "yahoo_symbol": "GOLTS.IS"},
    {"symbol": "GWIND", "name": "Galata Wind Enerji", "yahoo_symbol": "GWIND.IS"},
    {"symbol": "HLGYO", "name": "Halk GYO", "yahoo_symbol": "HLGYO.IS"},
    {"symbol": "IPEKE", "name": "İpek Enerji", "yahoo_symbol": "IPEKE.IS"},
    {"symbol": "ISMEN", "name": "İş Yatırım Menkul", "yahoo_symbol": "ISMEN.IS"},
    {"symbol": "KAYSE", "name": "Kayseri Şeker", "yahoo_symbol": "KAYSE.IS"},
    {"symbol": "KERVT", "name": "Kerevitaş Gıda", "yahoo_symbol": "KERVT.IS"},
    {"symbol": "KLSER", "name": "Kaleseramik", "yahoo_symbol": "KLSER.IS"},
    {"symbol": "KMPUR", "name": "Kempür", "yahoo_symbol": "KMPUR.IS"},
    {"symbol": "KORDS", "name": "Kordsa", "yahoo_symbol": "KORDS.IS"},
    {"symbol": "LOGO", "name": "Logo Yazılım", "yahoo_symbol": "LOGO.IS"},
    {"symbol": "MAVI", "name": "Mavi Giyim", "yahoo_symbol": "MAVI.IS"},
    {"symbol": "MPARK", "name": "MLP Sağlık", "yahoo_symbol": "MPARK.IS"},
    {"symbol": "ODAS", "name": "Odaş Elektrik", "yahoo_symbol": "ODAS.IS"},
    {"symbol": "OTKAR", "name": "Otokar", "yahoo_symbol": "OTKAR.IS"},
    {"symbol": "PAPIL", "name": "Papilon Savunma", "yahoo_symbol": "PAPIL.IS"},
    {"symbol": "PENTA", "name": "Penta Teknoloji", "yahoo_symbol": "PENTA.IS"},
    {"symbol": "QUAGR", "name": "QUA Granite", "yahoo_symbol": "QUAGR.IS"},
    {"symbol": "REEDR", "name": "Reedr Teknoloji", "yahoo_symbol": "REEDR.IS"},
    {"symbol": "SMRTG", "name": "Smart Güneş Enerji", "yahoo_symbol": "SMRTG.IS"},
    {"symbol": "SOKM", "name": "Şok Marketler", "yahoo_symbol": "SOKM.IS"},
    {"symbol": "TATGD", "name": "Tat Gıda", "yahoo_symbol": "TATGD.IS"},
    {"symbol": "TMSN", "name": "Tümosan Motor", "yahoo_symbol": "TMSN.IS"},
    {"symbol": "TRGYO", "name": "Torunlar GYO", "yahoo_symbol": "TRGYO.IS"},
    {"symbol": "TTKOM", "name": "Türk Telekom", "yahoo_symbol": "TTKOM.IS"},
    {"symbol": "TTRAK", "name": "Türk Traktör", "yahoo_symbol": "TTRAK.IS"},
    {"symbol": "ULKER", "name": "Ülker Bisküvi", "yahoo_symbol": "ULKER.IS"},
    {"symbol": "VAKBN", "name": "Vakıfbank", "yahoo_symbol": "VAKBN.IS"},
    {"symbol": "VESBE", "name": "Vestel Beyaz Eşya", "yahoo_symbol": "VESBE.IS"},
    {"symbol": "VESTL", "name": "Vestel Elektronik", "yahoo_symbol": "VESTL.IS"},
]

DEFAULT_INITIAL_CAPITAL = 100_000.0
