from pathlib import Path

CACHE_DIR = Path(__file__).resolve().parent.parent / "cache"
CACHE_TTL_SECONDS = 4 * 60 * 60  # 4 saat

BIST100: list[dict[str, str]] = [
    # BIST-30
    {"symbol": "AEFES", "name": "Anadolu Efes", "yahoo_symbol": "AEFES.IS"},
    {"symbol": "AKBNK", "name": "Akbank", "yahoo_symbol": "AKBNK.IS"},
    {"symbol": "ASELS", "name": "Aselsan", "yahoo_symbol": "ASELS.IS"},
    {"symbol": "ASTOR", "name": "Astor Enerji", "yahoo_symbol": "ASTOR.IS"},
    {"symbol": "BIMAS", "name": "BİM Mağazalar", "yahoo_symbol": "BIMAS.IS"},
    {"symbol": "DSTKF", "name": "Destek Finans Faktoring", "yahoo_symbol": "DSTKF.IS"},
    {"symbol": "EKGYO", "name": "Emlak Konut GYO", "yahoo_symbol": "EKGYO.IS"},
    {"symbol": "ENKAI", "name": "Enka İnşaat", "yahoo_symbol": "ENKAI.IS"},
    {"symbol": "EREGL", "name": "Ereğli Demir Çelik", "yahoo_symbol": "EREGL.IS"},
    {"symbol": "FROTO", "name": "Ford Otosan", "yahoo_symbol": "FROTO.IS"},
    {"symbol": "GARAN", "name": "Garanti BBVA", "yahoo_symbol": "GARAN.IS"},
    {"symbol": "GUBRF", "name": "Gübre Fabrikaları", "yahoo_symbol": "GUBRF.IS"},
    {"symbol": "ISCTR", "name": "İş Bankası C", "yahoo_symbol": "ISCTR.IS"},
    {"symbol": "KCHOL", "name": "Koç Holding", "yahoo_symbol": "KCHOL.IS"},
    {"symbol": "KRDMD", "name": "Kardemir D", "yahoo_symbol": "KRDMD.IS"},
    {"symbol": "MGROS", "name": "Migros Ticaret", "yahoo_symbol": "MGROS.IS"},
    {"symbol": "PETKM", "name": "Petkim", "yahoo_symbol": "PETKM.IS"},
    {"symbol": "PGSUS", "name": "Pegasus", "yahoo_symbol": "PGSUS.IS"},
    {"symbol": "SAHOL", "name": "Sabancı Holding", "yahoo_symbol": "SAHOL.IS"},
    {"symbol": "SASA", "name": "SASA Polyester", "yahoo_symbol": "SASA.IS"},
    {"symbol": "SISE", "name": "Şişecam", "yahoo_symbol": "SISE.IS"},
    {"symbol": "TAVHL", "name": "TAV Havalimanları", "yahoo_symbol": "TAVHL.IS"},
    {"symbol": "TCELL", "name": "Turkcell", "yahoo_symbol": "TCELL.IS"},
    {"symbol": "THYAO", "name": "Türk Hava Yolları", "yahoo_symbol": "THYAO.IS"},
    {"symbol": "TOASO", "name": "Tofaş Oto Fab.", "yahoo_symbol": "TOASO.IS"},
    {"symbol": "TRALT", "name": "Türk Altın İşletmeleri", "yahoo_symbol": "TRALT.IS"},
    {"symbol": "TTKOM", "name": "Türk Telekom", "yahoo_symbol": "TTKOM.IS"},
    {"symbol": "TUPRS", "name": "Tüpraş", "yahoo_symbol": "TUPRS.IS"},
    {"symbol": "ULKER", "name": "Ülker Bisküvi", "yahoo_symbol": "ULKER.IS"},
    {"symbol": "YKBNK", "name": "Yapı Kredi", "yahoo_symbol": "YKBNK.IS"},
    # BIST-100 (ek 69)
    {"symbol": "AGHOL", "name": "AG Anadolu Grubu Holding", "yahoo_symbol": "AGHOL.IS"},
    {"symbol": "AKSA", "name": "Aksa Akrilik", "yahoo_symbol": "AKSA.IS"},
    {"symbol": "AKSEN", "name": "Aksa Enerji", "yahoo_symbol": "AKSEN.IS"},
    {"symbol": "ALARK", "name": "Alarko Holding", "yahoo_symbol": "ALARK.IS"},
    {"symbol": "ALTNY", "name": "Altınay Savunma Teknolojileri", "yahoo_symbol": "ALTNY.IS"},
    {"symbol": "ANSGR", "name": "Anadolu Sigorta", "yahoo_symbol": "ANSGR.IS"},
    {"symbol": "ARCLK", "name": "Arçelik", "yahoo_symbol": "ARCLK.IS"},
    {"symbol": "BALSU", "name": "Balsu Gıda", "yahoo_symbol": "BALSU.IS"},
    {"symbol": "BRSAN", "name": "Borusan Mannesmann Boru", "yahoo_symbol": "BRSAN.IS"},
    {"symbol": "BRYAT", "name": "Borusan Yatırım", "yahoo_symbol": "BRYAT.IS"},
    {"symbol": "BSOKE", "name": "Batısöke Çimento", "yahoo_symbol": "BSOKE.IS"},
    {"symbol": "BTCIM", "name": "Batıçim", "yahoo_symbol": "BTCIM.IS"},
    {"symbol": "CANTE", "name": "Çan2 Termik", "yahoo_symbol": "CANTE.IS"},
    {"symbol": "CCOLA", "name": "Coca-Cola İçecek", "yahoo_symbol": "CCOLA.IS"},
    {"symbol": "CIMSA", "name": "Çimsa Çimento", "yahoo_symbol": "CIMSA.IS"},
    {"symbol": "DAPGM", "name": "DAP Gayrimenkul", "yahoo_symbol": "DAPGM.IS"},
    {"symbol": "DOAS", "name": "Doğuş Otomotiv", "yahoo_symbol": "DOAS.IS"},
    {"symbol": "DOHOL", "name": "Doğan Holding", "yahoo_symbol": "DOHOL.IS"},
    {"symbol": "ECILC", "name": "Eczacıbaşı İlaç", "yahoo_symbol": "ECILC.IS"},
    {"symbol": "EFOR", "name": "Efor Yatırım Holding", "yahoo_symbol": "EFOR.IS"},
    {"symbol": "EGEEN", "name": "Ege Endüstri", "yahoo_symbol": "EGEEN.IS"},
    {"symbol": "ENERY", "name": "Enerya Enerji", "yahoo_symbol": "ENERY.IS"},
    {"symbol": "ENJSA", "name": "Enerjisa Enerji", "yahoo_symbol": "ENJSA.IS"},
    {"symbol": "EUPWR", "name": "Europower Enerji", "yahoo_symbol": "EUPWR.IS"},
    {"symbol": "FENER", "name": "Fenerbahçe Futbol", "yahoo_symbol": "FENER.IS"},
    {"symbol": "GENIL", "name": "Gen İlaç", "yahoo_symbol": "GENIL.IS"},
    {"symbol": "GESAN", "name": "Girişim Elektrik", "yahoo_symbol": "GESAN.IS"},
    {"symbol": "GLRMK", "name": "Gülermak Ağır Sanayi", "yahoo_symbol": "GLRMK.IS"},
    {"symbol": "GRSEL", "name": "Gür-Sel Turizm", "yahoo_symbol": "GRSEL.IS"},
    {"symbol": "GRTHO", "name": "Grainturk Holding", "yahoo_symbol": "GRTHO.IS"},
    {"symbol": "GSRAY", "name": "Galatasaray Sportif", "yahoo_symbol": "GSRAY.IS"},
    {"symbol": "HALKB", "name": "Halkbank", "yahoo_symbol": "HALKB.IS"},
    {"symbol": "HEKTS", "name": "Hektaş Ticaret", "yahoo_symbol": "HEKTS.IS"},
    {"symbol": "ISMEN", "name": "İş Yatırım Menkul", "yahoo_symbol": "ISMEN.IS"},
    {"symbol": "IZENR", "name": "İzdemir Enerji", "yahoo_symbol": "IZENR.IS"},
    {"symbol": "KCAER", "name": "Kocaer Çelik", "yahoo_symbol": "KCAER.IS"},
    {"symbol": "KLRHO", "name": "Kiler Holding", "yahoo_symbol": "KLRHO.IS"},
    {"symbol": "KONTR", "name": "Kontrolmatik", "yahoo_symbol": "KONTR.IS"},
    {"symbol": "KTLEV", "name": "Katılımevim Tasarruf Finansman", "yahoo_symbol": "KTLEV.IS"},
    {"symbol": "KUYAS", "name": "Kuyumcukent Gayrimenkul", "yahoo_symbol": "KUYAS.IS"},
    {"symbol": "MAGEN", "name": "Margün Enerji", "yahoo_symbol": "MAGEN.IS"},
    {"symbol": "MAVI", "name": "Mavi Giyim", "yahoo_symbol": "MAVI.IS"},
    {"symbol": "MIATK", "name": "Mia Teknoloji", "yahoo_symbol": "MIATK.IS"},
    {"symbol": "MPARK", "name": "MLP Sağlık", "yahoo_symbol": "MPARK.IS"},
    {"symbol": "OBAMS", "name": "Oba Makarnacılık", "yahoo_symbol": "OBAMS.IS"},
    {"symbol": "ODAS", "name": "Odaş Elektrik", "yahoo_symbol": "ODAS.IS"},
    {"symbol": "OTKAR", "name": "Otokar", "yahoo_symbol": "OTKAR.IS"},
    {"symbol": "OYAKC", "name": "Oyak Çimento", "yahoo_symbol": "OYAKC.IS"},
    {"symbol": "PASEU", "name": "Pasifik Eurasia Lojistik", "yahoo_symbol": "PASEU.IS"},
    {"symbol": "PATEK", "name": "Pasifik Teknoloji", "yahoo_symbol": "PATEK.IS"},
    {"symbol": "QUAGR", "name": "QUA Granite", "yahoo_symbol": "QUAGR.IS"},
    {"symbol": "RALYH", "name": "Ral Yatırım Holding", "yahoo_symbol": "RALYH.IS"},
    {"symbol": "REEDR", "name": "Reeder Teknoloji", "yahoo_symbol": "REEDR.IS"},
    {"symbol": "SKBNK", "name": "Şekerbank", "yahoo_symbol": "SKBNK.IS"},
    {"symbol": "SOKM", "name": "Şok Marketler", "yahoo_symbol": "SOKM.IS"},
    {"symbol": "TABGD", "name": "TAB Gıda", "yahoo_symbol": "TABGD.IS"},
    {"symbol": "TKFEN", "name": "Tekfen Holding", "yahoo_symbol": "TKFEN.IS"},
    {"symbol": "TRENJ", "name": "TR Doğal Enerji Kaynakları", "yahoo_symbol": "TRENJ.IS"},
    {"symbol": "TRMET", "name": "TR Anadolu Metal Madencilik", "yahoo_symbol": "TRMET.IS"},
    {"symbol": "TSKB", "name": "Türkiye Sınai Kalkınma Bankası", "yahoo_symbol": "TSKB.IS"},
    {"symbol": "TSPOR", "name": "Trabzonspor Sportif", "yahoo_symbol": "TSPOR.IS"},
    {"symbol": "TTRAK", "name": "Türk Traktör", "yahoo_symbol": "TTRAK.IS"},
    {"symbol": "TUKAS", "name": "Tukaş Gıda", "yahoo_symbol": "TUKAS.IS"},
    {"symbol": "TUREX", "name": "Tureks Turizm Taşımacılık", "yahoo_symbol": "TUREX.IS"},
    {"symbol": "TURSG", "name": "Türkiye Sigorta", "yahoo_symbol": "TURSG.IS"},
    {"symbol": "VAKBN", "name": "Vakıfbank", "yahoo_symbol": "VAKBN.IS"},
    {"symbol": "VESTL", "name": "Vestel Elektronik", "yahoo_symbol": "VESTL.IS"},
    {"symbol": "YEOTK", "name": "YEO Teknoloji Enerji", "yahoo_symbol": "YEOTK.IS"},
    {"symbol": "ZOREN", "name": "Zorlu Enerji", "yahoo_symbol": "ZOREN.IS"},
]

DEFAULT_INITIAL_CAPITAL = 100_000.0
